round_name: '1'
mode: "step_mcts"
model_dir: "deepseek-ai/deepseek-math-7b-instruct"
ref_model_dir: "deepseek-ai/deepseek-math-7b-instruct"
swap_space: 16
temperature: 1
errors_threshold: 3
step_delim: ""
stop: ["<｜end▁of▁sentence｜>","\n\n"]
max_depth: 8
n_generate_sample: 5
iterations: 80
seed: 42
is_sampling: True
verbose: False
top_k: 5
best_of: 5
batch_size: 256
update_on_step: False
ref_batch_size: 8
model_api: 'http://localhost:9554/v1'
ref_model_api: 'http://localhost:8554/v1'
remove_duplicate: True
need_ref_model: False
model_type: server
positive_reward: 1
negative_reward: -1
parallel_type: thread